services:
  - type: web
    name: nextjs-fullstack
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    branch: main
    rootDir: .
    autoDeploy: true